### ISSUE TITLE
Error: Cannot find module 'lodash/string'

### ISSUE THREAD

**Issue by MrCoder** [prograhammer/vue-library-template#5]
OS: macOS Sierra
npm: v5.3.0
node: v6.10.3

Command line: `vue init prograhammer/vue-library-template sequence-drawer`

Error:
````
module.js:471
    throw err;
    ^

Error: Cannot find module 'lodash/string'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/twer/.vue-templates/prograhammer-vue-library-template/meta.js:1:71)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getMetadata (/Users/twer/.nvm/versions/node/v6.10.3/lib/node_modules/vue-cli/lib/options.js:43:15)
    at options (/Users/twer/.nvm/versions/node/v6.10.3/lib/node_modules/vue-cli/lib/options.js:15:14)
    at generate (/Users/twer/.nvm/versions/node/v6.10.3/lib/node_modules/vue-cli/lib/generate.js:36:14)
    at /Users/twer/.nvm/versions/node/v6.10.3/lib/node_modules/vue-cli/bin/vue-init:153:5
````

**Comment by prograhammer** [comment]
Ahh, my apologies! I put in a pure js function instead of lodash. Fixed!
